import type { ReactElement } from "react";
import Layout from "../components/Layout/Layout";
import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";

const Page: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Natours | Exciting tours for adventurous people</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="title"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Header />
        <Main />
      </main>
    </div>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Page;
